// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVxgtCvOTuHGqJuNbSAOAnFyW-C_if54',
    appId: '1:1004223604376:web:92d065bd2db6d3c20092ed',
    messagingSenderId: '1004223604376',
    projectId: 'badminfinder-84d4d',
    authDomain: 'badminfinder-84d4d.firebaseapp.com',
    storageBucket: 'badminfinder-84d4d.firebasestorage.app',
    measurementId: 'G-SEKMC4NF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghhLXhTBF4ecroZinsU5JXIBy81updLo',
    appId: '1:1004223604376:android:6956483b8e30e3960092ed',
    messagingSenderId: '1004223604376',
    projectId: 'badminfinder-84d4d',
    storageBucket: 'badminfinder-84d4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ojz5qZ6BuJbSMsAg4B-d54-anl8QOuY',
    appId: '1:1004223604376:ios:b95692bf708289b20092ed',
    messagingSenderId: '1004223604376',
    projectId: 'badminfinder-84d4d',
    storageBucket: 'badminfinder-84d4d.firebasestorage.app',
    iosBundleId: 'com.teamtrow.victor',
  );
}
